name: deploy

on:
  workflow_dispatch:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing deploy command
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 194.58.109.120
        username: root
        password: VKe9@*o:4mCr
        port: 22
        script: |
          cd /root/mika-site

          git pull origin

          git checkout master
          git pull origin master
          docker compose up --build -d
